version: '3'
services:
  php-fpm:
    build: ./php-fpm
    restart: always
    env_file:
      - php-fpm/.env
    volumes:
      - ./laravel:/srv/caddy/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - mysql/.env
    ports:
      - 3306:3306
    volumes:
      - ./tmp/mysql/datadir:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

  caddy:
    build: ./caddy
    restart: always
    env_file:
      - caddy/.env
    ports:
      - 443:443
    volumes:
      - ./tmp/ssl:/srv/caddy/ssl
      - ./laravel:/srv/caddy/html
    links:
      - php-fpm
